"use client";
import { useCallback, useEffect, useState, type ReactNode } from "react";
import { Button, Card, Empty, Eyebrow } from "../ui/primitives";
import { ApiError, api, type ApiUser, type DictionaryEntry, type DictionaryMeaning, type ProgressAttempt, type SkillState, type VocabularyItem } from "../shared/api/client";

function messageFor(cause: unknown) { return cause instanceof ApiError ? cause.message : "Something went wrong. Please try again."; }
function LoadState({ children }: { children: ReactNode }) { return <p className="muted" aria-live="polite">{children}</p>; }

export function Progress({ token, onReview }: { token: string; onReview: (attemptId: string) => void }) {
  const [attempts, setAttempts] = useState<ProgressAttempt[] | null>(null); const [skills, setSkills] = useState<SkillState[] | null>(null); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { setError(null); try { const [progress, skillResponse] = await Promise.all([api.progress(token), api.skills(token)]); setAttempts(progress.attempts); setSkills(skillResponse.skills); } catch (cause) { setError(messageFor(cause)); } }, [token]);
  useEffect(() => { void load(); }, [load]);
  const completed = attempts?.filter(attempt => attempt.status === "completed").length ?? 0;
  return <div className="page"><Eyebrow>Your progress</Eyebrow><h1>Built through<br /><i>practice.</i></h1>{error && <Card><p role="alert">{error}</p><Button variant="secondary" onClick={() => void load()}>Try again</Button></Card>}{!attempts || !skills ? <LoadState>Loading your practice history…</LoadState> : <><div className="progress-summary"><Card><span>Completed practices</span><strong>{completed}</strong><small>Analyzed attempts only</small></Card><Card><span>All attempts</span><strong>{attempts.length}</strong><small>Including work still in progress</small></Card><Card><span>Skill signals</span><strong>{skills.length}</strong><small>Evidence-backed skill states</small></Card></div><section className="skill-list"><Eyebrow>Skill snapshot</Eyebrow>{skills.length ? skills.map(skill => <div key={skill.skill}><span>{skill.skill}</span><i><b style={{ width: `${Math.round(Math.max(0, Math.min(1, skill.estimatedLevel)) * 100)}%` }} /></i><strong>{Math.round(skill.estimatedLevel * 100)}</strong><small>{Math.round(skill.confidence * 100)}% confidence</small></div>) : <Empty title="No skill snapshot yet" body="Your skill evidence will appear after an analyzed practice." />}</section><section className="attempt-list"><Eyebrow>Practice history</Eyebrow>{attempts.length ? attempts.map(attempt => <Card key={attempt.id}><div><h2>{attempt.challenge.prompt}</h2><p>{new Date(attempt.createdAt).toLocaleDateString()}</p></div>{attempt.status === "completed" ? <Button variant="secondary" onClick={() => onReview(attempt.id)}>Review</Button> : <span className="pill">{attempt.status.replaceAll("_", " ")}</span>}</Card>) : <Empty title="No practices yet" body="Complete a speaking challenge to begin your progress history." />}</section></>}</div>;
}

function words(value: unknown) { return Array.isArray(value) ? value.filter((item): item is string => typeof item === "string" && item.trim().length > 0) : []; }
function meanings(entry: DictionaryEntry) { return Array.isArray(entry.payload.meanings) ? entry.payload.meanings.filter((meaning): meaning is DictionaryMeaning => typeof meaning === "object" && meaning !== null) : []; }
function lexicalTerms(entry: DictionaryEntry, key: "synonyms" | "antonyms") { return [...words(entry.payload[key]), ...meanings(entry).flatMap(meaning => words(meaning[key]))].filter((word, index, all) => all.indexOf(word) === index); }
function DictionaryDetails({ entry }: { entry: DictionaryEntry }) { const definitionGroups = meanings(entry); const examples = [...words(entry.payload.examples), ...definitionGroups.flatMap(meaning => words(meaning.examples))]; const synonyms = lexicalTerms(entry, "synonyms"); const antonyms = lexicalTerms(entry, "antonyms"); return <div className="dictionary-details"><>{entry.payload.phonetic && <p>Pronunciation: /{entry.payload.phonetic.replace(/^\/+|\/+$/g, "")}/</p>}{definitionGroups.map((meaning, index) => <div key={`${meaning.partOfSpeech ?? "definition"}-${index}`}><strong>{meaning.partOfSpeech ?? "Definition"}</strong>{words(meaning.definitions).length ? <ul>{words(meaning.definitions).map(definition => <li key={definition}>{definition}</li>)}</ul> : null}</div>)}{examples.length ? <div><strong>Examples</strong><ul>{examples.map(example => <li key={example}>{example}</li>)}</ul></div> : null}{synonyms.length ? <p><strong>Synonyms:</strong> {synonyms.join(", ")}</p> : null}{antonyms.length ? <p><strong>Antonyms:</strong> {antonyms.join(", ")}</p> : null}<p className="muted">Source: {entry.source}{entry.expiresAt ? ` · Cached until ${new Date(entry.expiresAt).toLocaleDateString()}` : ""}</p></></div>; }

export function Vocabulary({ token }: { token: string }) {
  const [items, setItems] = useState<VocabularyItem[] | null>(null); const [word, setWord] = useState(""); const [preview, setPreview] = useState<DictionaryEntry | null | undefined>(undefined); const [openItems, setOpenItems] = useState<string[]>([]); const [error, setError] = useState<string | null>(null); const [action, setAction] = useState<string | null>(null);
  const load = useCallback(async () => { setError(null); try { setItems((await api.vocabulary(token)).items); } catch (cause) { setError(messageFor(cause)); } }, [token]);
  useEffect(() => { void load(); }, [load]);
  const lookup = async () => { const value = word.trim(); if (!value) return; setAction("lookup"); setError(null); try { setPreview((await api.lookupDictionary(token, value)).dictionary); } catch (cause) { setError(messageFor(cause)); } finally { setAction(null); } };
  const add = async () => { const value = word.trim(); if (!value) return; setAction("add"); setError(null); try { const item = await api.addVocabulary(token, value, preview !== null); setItems(current => current ? [...current, item].sort((left, right) => left.word.localeCompare(right.word)) : [item]); setWord(""); setPreview(undefined); } catch (cause) { setError(messageFor(cause)); } finally { setAction(null); } };
  const update = async (item: VocabularyItem, practiceStatus: VocabularyItem["practiceStatus"]) => { setAction(item.id); setError(null); try { const next = await api.updateVocabulary(token, item.id, practiceStatus); setItems(current => current?.map(value => value.id === next.id ? next : value) ?? current); } catch (cause) { setError(messageFor(cause)); await load(); } finally { setAction(null); } };
  const remove = async (item: VocabularyItem) => { setAction(item.id); setError(null); try { await api.deleteVocabulary(token, item.id); setItems(current => current?.filter(value => value.id !== item.id) ?? current); } catch (cause) { setError(messageFor(cause)); await load(); } finally { setAction(null); } };
  return <div className="page vocabulary"><Eyebrow>Your word bank</Eyebrow><h1>Words worth<br /><i>reaching for.</i></h1><div className="add-word"><input value={word} disabled={action !== null} onChange={event => { setWord(event.target.value); setPreview(undefined); }} onKeyDown={event => { if (event.key === "Enter") void lookup(); }} placeholder="Add a word or phrase" aria-label="New vocabulary word" /><Button variant="secondary" disabled={action !== null || !word.trim()} onClick={() => void lookup()}>{action === "lookup" ? "Looking up…" : "Look up"}</Button><Button disabled={action !== null || !word.trim()} onClick={() => void add()}>{action === "add" ? "Saving…" : "Save word"}</Button></div>{preview !== undefined && <Card className="dictionary-preview">{preview ? <><Eyebrow>Dictionary preview</Eyebrow><h2>{preview.term}</h2><DictionaryDetails entry={preview} /></> : <><h2>No dictionary entry found</h2><p>You can still save this word as a personal vocabulary item without a definition.</p></>}</Card>}{error && <Card><p role="alert">{error}</p><Button variant="secondary" onClick={() => void load()}>Refresh list</Button></Card>}{!items ? <LoadState>Loading your word bank…</LoadState> : items.length ? <div className="word-list">{items.map(item => { const expanded = openItems.includes(item.id); const busy = action === item.id; return <Card key={item.id}><div><h2>{item.word}</h2>{item.dictionary ? <><p>{item.dictionary.payload.phonetic ? `/${item.dictionary.payload.phonetic.replace(/^\/+|\/+$/g, "")}/` : "Dictionary entry available."}</p><button className="text-link" type="button" aria-expanded={expanded} onClick={() => setOpenItems(current => expanded ? current.filter(id => id !== item.id) : [...current, item.id])}>{expanded ? "Hide details" : "Show details"}</button>{expanded && <DictionaryDetails entry={item.dictionary} />}</> : <p>No dictionary entry is attached to this personal item.</p>}</div><div><label className="sr-only" htmlFor={`status-${item.id}`}>Practice status for {item.word}</label><select id={`status-${item.id}`} value={item.practiceStatus} disabled={busy} onChange={event => void update(item, event.target.value)}><option value="new">New</option><option value="learning">Learning</option><option value="practicing">Practicing</option><option value="mastered">Mastered</option></select><button className="icon-button" type="button" disabled={busy} onClick={() => void remove(item)} aria-label={`Delete ${item.word}`}>×</button></div></Card>; })}</div> : <Empty title="Your word bank is empty" body="Save precise words and phrases you want to make your own." />}</div>;
}

type ProfilePreferences = { displayName?: string; practiceLanguage?: string; recordingAnalysisConsent?: boolean };
export function Profile({ token, user, onSaved, onSignOut }: { token: string; user: ApiUser; onSaved: (user: ApiUser) => void; onSignOut: () => void }) {
  const preferences = user.preferences as ProfilePreferences; const [displayName, setDisplayName] = useState(preferences.displayName ?? ""); const [practiceLanguage, setPracticeLanguage] = useState(preferences.practiceLanguage ?? "English"); const [recordingAnalysisConsent, setRecordingAnalysisConsent] = useState(preferences.recordingAnalysisConsent ?? true); const [status, setStatus] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  const save = async () => { setSaving(true); setError(null); setStatus(null); try { const next = await api.updatePreferences(token, { ...user.preferences, displayName: displayName.trim(), practiceLanguage, recordingAnalysisConsent }); onSaved(next); setStatus("Profile saved."); } catch (cause) { setError(messageFor(cause)); } finally { setSaving(false); } };
  return <div className="page profile narrow"><Eyebrow>Account</Eyebrow><h1>Your profile</h1><Card><label>Display name<input value={displayName} onChange={event => setDisplayName(event.target.value)} autoComplete="name" /></label><label>Email<input type="email" value={user.email} disabled aria-describedby="email-note" /></label><p id="email-note" className="muted">Email changes are not available yet.</p><label>Practice language<select value={practiceLanguage} onChange={event => setPracticeLanguage(event.target.value)}><option>English</option><option>Hindi</option></select></label><Button disabled={saving} onClick={() => void save()}>{saving ? "Saving…" : "Save changes"}</Button>{status && <p role="status">{status}</p>}{error && <p className="form-error" role="alert">{error}</p>}</Card><Card><h2>Recording privacy</h2><p>Recordings are private. Once storage is enabled, this setting controls whether a recording may be analyzed to generate feedback.</p><label className="check"><input type="checkbox" checked={recordingAnalysisConsent} onChange={event => setRecordingAnalysisConsent(event.target.checked)} /> Allow analysis of my recordings</label></Card><button className="text-link danger" onClick={onSignOut}>Sign out</button></div>;
}
