"use client";

import { FormEvent, useEffect, useState } from "react";
import { ApiError, api, type ApiUser, type AuthResponse } from "../shared/api/client";
import { Button, Card, Eyebrow } from "../ui/primitives";
import type { View } from "../ui/shell";

export function Landing({ go }: { go: (v: View) => void }) {
  return <div className="landing"><div className="landing-nav"><span className="brand">oratry<span>.</span></span><Button variant="quiet" onClick={() => go("signup")}>Sign in</Button></div><div className="hero"><Eyebrow>Deliberate speaking practice</Eyebrow><h1>Speak with<br /><i>intent.</i></h1><p>Build the habits behind clear, confident communication — one focused practice at a time.</p><Button onClick={() => go("signup")}>Start practicing <span aria-hidden>→</span></Button></div><div className="hero-note">Structured challenges · private recordings · one clear focus</div></div>;
}

export function Signup({ go, onAuthenticated }: { go: (v: View) => void; onAuthenticated: (result: AuthResponse) => void }) {
  const [isSignIn, setIsSignIn] = useState(false); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [acceptedTerms, setAcceptedTerms] = useState(false); const [error, setError] = useState<string | null>(null); const [submitting, setSubmitting] = useState(false); const [activationEmail, setActivationEmail] = useState<string | null>(null); const [resendStatus, setResendStatus] = useState<string | null>(null); const [localActivationUrl, setLocalActivationUrl] = useState<string | null>(null); const [googleAvailable, setGoogleAvailable] = useState(false);
  useEffect(() => { void api.authProviders().then(result => setGoogleAvailable(result.google)).catch(() => setGoogleAvailable(false)); }, []);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(null); setSubmitting(true); try { if (isSignIn) { onAuthenticated(await api.signIn(email, password)); go("home"); } else { const result = await api.signUp(email, password, acceptedTerms); setActivationEmail(result.user.email); } } catch (cause) { const next = cause instanceof ApiError ? cause : null; setError(next?.message ?? "Something went wrong. Please try again."); if (isSignIn && next?.code === "email_verification_required") setActivationEmail(email.trim().toLowerCase()); } finally { setSubmitting(false); } }
  async function resend() { if (!activationEmail) return; setSubmitting(true); setError(null); try { await api.resendActivation(activationEmail); setResendStatus("If this address has an unverified Oratry account, we sent a fresh activation link."); } catch (cause) { setError(cause instanceof ApiError ? cause.message : "We couldn't resend the link. Try again."); } finally { setSubmitting(false); } }
  async function findLocalLink() { if (!activationEmail) return; setError(null); try { const outbox = await api.developmentOutbox(); const message = [...outbox.messages].reverse().find(item => item.recipient.toLowerCase() === activationEmail.toLowerCase()); if (!message) setError("No local activation message is available yet."); else setLocalActivationUrl(message.activationUrl); } catch { setError("The local activation preview is unavailable. Check the API is running in local mode."); } }
  function continueWithGoogle() { if (!isSignIn && !acceptedTerms) { setError("Accept the terms before creating an account with Google."); return; } window.location.assign(api.googleStartUrl(!isSignIn && acceptedTerms)); }
  if (activationEmail) return <div className="auth"><div><span className="brand">oratry<span>.</span></span><Eyebrow>One more step</Eyebrow><h1>Check your<br />inbox.</h1><p>We sent an activation link to {activationEmail}. Activate your account before signing in.</p></div><Card><h2>Activate your account</h2><p>Open the email and follow its one-time link. It expires for your protection.</p>{resendStatus && <p role="status">{resendStatus}</p>}{error && <p className="form-error" role="alert">{error}</p>}<Button onClick={() => void resend()} disabled={submitting}>{submitting ? "Please wait…" : "Resend activation link"}</Button>{process.env.NODE_ENV === "development" && <p className="muted">Local preview only: <button type="button" onClick={() => void findLocalLink()}>find the local activation link</button></p>}{localActivationUrl && <p><a href={localActivationUrl}>Open local activation link</a></p>}<p className="muted"><button type="button" onClick={() => { setActivationEmail(null); setResendStatus(null); setLocalActivationUrl(null); setIsSignIn(true); }}>Back to sign in</button></p></Card></div>;
  return <div className="auth"><div><span className="brand">oratry<span>.</span></span><Eyebrow>Your practice starts here</Eyebrow><h1>Make your words<br />count.</h1><p>Two minutes of thoughtful speaking can change the way you show up.</p></div><Card className="auth-card"><h2>{isSignIn ? "Welcome back" : "Create your account"}</h2><p className="auth-subtitle">{isSignIn ? "Pick up where your last practice left off." : "A quiet space to practise clearer thinking aloud."}</p><button type="button" className="oauth-button" disabled={!googleAvailable} onClick={continueWithGoogle}><span aria-hidden="true">G</span>{googleAvailable ? "Continue with Google" : "Google sign-in is being configured"}</button><div className="auth-divider"><span>or continue with email</span></div><form onSubmit={submit}><label>Email<input type="email" value={email} onChange={event => setEmail(event.target.value)} placeholder="you@example.com" autoComplete="email" required /></label><label>Password<input type="password" value={password} onChange={event => setPassword(event.target.value)} placeholder="At least 8 characters" autoComplete={isSignIn ? "current-password" : "new-password"} minLength={8} required /></label>{!isSignIn && <label className="check"><input type="checkbox" checked={acceptedTerms} onChange={event => setAcceptedTerms(event.target.checked)} /> I agree to the terms and privacy policy.</label>}{error && <p className="form-error" role="alert">{error}</p>}<Button type="submit" disabled={submitting}>{submitting ? "Please wait…" : isSignIn ? "Sign in" : "Create account"}</Button></form><p className="muted">{isSignIn ? "New to Oratry?" : "Already have an account?"} <button type="button" onClick={() => { setError(null); setIsSignIn(value => !value); }}>{isSignIn ? "Create an account" : "Sign in"}</button></p></Card></div>;
}

export function GoogleCallback({ go, onAuthenticated }: { go: (v: View) => void; onAuthenticated: (result: AuthResponse) => void }) {
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { const params = new URLSearchParams(window.location.search); const code = params.get("code"); const providerError = params.get("error"); if (providerError || !code) { setError(providerError === "terms_required" ? "Accept the terms before creating a new account with Google." : "Google sign-in was cancelled, expired, or could not be verified."); return; } void api.completeGoogleLogin(code).then(result => { onAuthenticated(result); go("onboarding"); }).catch(cause => setError(cause instanceof ApiError ? cause.message : "Google sign-in could not be completed.")); }, [go, onAuthenticated]);
  return <div className="processing narrow"><Eyebrow>{error ? "Sign-in unavailable" : "Signing you in"}</Eyebrow><h1>{error ? "Let’s try that again." : "Welcome to Oratry."}</h1>{error ? <><p role="alert">{error}</p><Button onClick={() => go("signup")}>Return to sign in</Button></> : <div className="orb" />}</div>;
}

export function Activation({ go, onAuthenticated }: { go: (v: View) => void; onAuthenticated: (result: AuthResponse) => void }) {
  const [state, setState] = useState<"loading" | "invalid">("loading"); const [error, setError] = useState<string | null>(null);
  useEffect(() => { const token = new URLSearchParams(window.location.search).get("token"); if (!token) { setError("This activation link is missing its token."); setState("invalid"); return; } void api.activate(token).then(result => { onAuthenticated(result); go("onboarding"); }).catch(cause => { setError(cause instanceof ApiError ? cause.message : "We couldn't activate this account."); setState("invalid"); }); }, [go, onAuthenticated]);
  return <div className="processing narrow"><Eyebrow>{state === "loading" ? "Activating account" : "Activation unavailable"}</Eyebrow><h1>{state === "loading" ? "Just a moment…" : "This link can’t be used."}</h1>{state === "loading" ? <div className="orb" /> : <><p role="alert">{error}</p><Button onClick={() => go("signup")}>Return to sign in</Button></>}</div>;
}

export function Onboarding({ go, token, user, onPreferencesSaved }: { go: (v: View) => void; token: string; user: ApiUser; onPreferencesSaved: (user: ApiUser) => void }) {
  const choices = ["Speak more clearly", "Organize my thoughts", "Find words faster", "Speak with more variety"]; const painPointOptions = ["I lose my thread", "I rush through ideas", "I repeat words", "I need better word choice"]; const [selected, setSelected] = useState<string[]>(() => Array.isArray(user.preferences.learningGoals) ? user.preferences.learningGoals.filter((item): item is string => typeof item === "string") : []); const [painPoints, setPainPoints] = useState<string[]>(() => Array.isArray(user.preferences.painPoints) ? user.preferences.painPoints.filter((item): item is string => typeof item === "string") : []); const [weeklyPracticeMinutes, setWeeklyPracticeMinutes] = useState(String(user.preferences.weeklyPracticeMinutes ?? 30)); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  function toggle(choice: string) { setSelected(current => current.includes(choice) ? current.filter(item => item !== choice) : current.length < 2 ? [...current, choice] : current); }
  function togglePainPoint(choice: string) { setPainPoints(current => current.includes(choice) ? current.filter(item => item !== choice) : [...current, choice]); }
  async function continueOnboarding() { setSaving(true); setError(null); try { const next = await api.updatePreferences(token, { ...user.preferences, learningGoals: selected, painPoints, weeklyPracticeMinutes: Number(weeklyPracticeMinutes) }); onPreferencesSaved(next); go("baseline"); } catch (cause) { setError(cause instanceof ApiError ? cause.message : "We couldn't save your choices. Try again."); } finally { setSaving(false); } }
  return <div className="onboarding narrow"><Eyebrow>01 / 02</Eyebrow><h1>What would you like to improve?</h1><p>Select up to two areas. We’ll use this to tailor your first practice.</p><div className="choice-grid">{choices.map(choice => <button key={choice} type="button" className={`choice ${selected.includes(choice) ? "selected" : ""}`} aria-pressed={selected.includes(choice)} onClick={() => toggle(choice)}>{choice}<span>{selected.includes(choice) ? "✓" : "+"}</span></button>)}</div><h2>What gets in your way?</h2><div className="choice-grid">{painPointOptions.map(choice => <button key={choice} type="button" className={`choice ${painPoints.includes(choice) ? "selected" : ""}`} aria-pressed={painPoints.includes(choice)} onClick={() => togglePainPoint(choice)}>{choice}<span>{painPoints.includes(choice) ? "✓" : "+"}</span></button>)}</div><label>Planned practice time each week<select value={weeklyPracticeMinutes} onChange={event => setWeeklyPracticeMinutes(event.target.value)}><option value="15">15 minutes</option><option value="30">30 minutes</option><option value="60">1 hour</option></select></label>{error && <p className="form-error" role="alert">{error}</p>}<Button onClick={continueOnboarding} disabled={saving}>{saving ? "Saving…" : "Continue"}</Button></div>;
}

export function Baseline({ go, token, onStarted }: { go: (v: View) => void; token: string; onStarted: () => Promise<void> }) {
  const [error, setError] = useState<string | null>(null); const [starting, setStarting] = useState(false);
  async function begin() { setStarting(true); setError(null); try { await api.startBaseline(token); await onStarted(); go("home"); } catch (cause) { setError(cause instanceof ApiError ? cause.message : "We couldn't start your baseline. Try again."); } finally { setStarting(false); } }
  return <div className="baseline narrow"><Eyebrow>Your starting point</Eyebrow><h1>Let’s find your<br /><i>baseline.</i></h1><p>You’ll complete three short speaking challenges. There are no right answers — this simply gives us a place to begin.</p><Card><span className="step-number">3</span><div><h3>Short challenges</h3><p>About 2 minutes each</p></div><span className="step-number">15</span><div><h3>Minutes total</h3><p>Take them when you’re ready</p></div></Card>{error && <p className="form-error" role="alert">{error}</p>}<Button onClick={begin} disabled={starting}>{starting ? "Starting…" : "Begin baseline"}</Button></div>;
}
