"use client";

import { FormEvent, useState } from "react";
import { ApiError, api, type AuthResponse } from "../shared/api/client";
import { Button, Card, Eyebrow } from "../ui/primitives";
import type { View } from "../ui/shell";

export function Landing({ go }: { go: (v: View) => void }) {
  return <div className="landing"><div className="landing-nav"><span className="brand">oratry<span>.</span></span><Button variant="quiet" onClick={() => go("signup")}>Sign in</Button></div><div className="hero"><Eyebrow>Deliberate speaking practice</Eyebrow><h1>Speak with<br /><i>intent.</i></h1><p>Build the habits behind clear, confident communication — one focused practice at a time.</p><Button onClick={() => go("signup")}>Start practicing <span aria-hidden>→</span></Button></div><div className="hero-note">Structured challenges · private recordings · one clear focus</div></div>;
}

export function Signup({ go, onAuthenticated }: { go: (v: View) => void; onAuthenticated: (result: AuthResponse) => void }) {
  const [isSignIn, setIsSignIn] = useState(false); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [acceptedTerms, setAcceptedTerms] = useState(false); const [error, setError] = useState<string | null>(null); const [submitting, setSubmitting] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(null); setSubmitting(true); try { const result = isSignIn ? await api.signIn(email, password) : await api.signUp(email, password, acceptedTerms); onAuthenticated(result); go(isSignIn ? "home" : "onboarding"); } catch (cause) { setError(cause instanceof ApiError ? cause.message : "Something went wrong. Please try again."); } finally { setSubmitting(false); } }
  return <div className="auth"><div><span className="brand">oratry<span>.</span></span><Eyebrow>Your practice starts here</Eyebrow><h1>Make your words<br />count.</h1><p>Two minutes of thoughtful speaking can change the way you show up.</p></div><Card><h2>{isSignIn ? "Welcome back" : "Create your account"}</h2><form onSubmit={submit}><label>Email<input type="email" value={email} onChange={event => setEmail(event.target.value)} placeholder="you@example.com" autoComplete="email" required /></label><label>Password<input type="password" value={password} onChange={event => setPassword(event.target.value)} placeholder="At least 8 characters" autoComplete={isSignIn ? "current-password" : "new-password"} minLength={8} required /></label>{!isSignIn && <label className="check"><input type="checkbox" checked={acceptedTerms} onChange={event => setAcceptedTerms(event.target.checked)} required /> I agree to the terms and privacy policy.</label>}{error && <p className="form-error" role="alert">{error}</p>}<Button type="submit" disabled={submitting}>{submitting ? "Please wait…" : isSignIn ? "Sign in" : "Create account"}</Button></form><p className="muted">{isSignIn ? "New to Oratry?" : "Already have an account?"} <button type="button" onClick={() => { setError(null); setIsSignIn(value => !value); }}>{isSignIn ? "Create an account" : "Sign in"}</button></p></Card></div>;
}

export function Onboarding({ go, token, onPreferencesSaved }: { go: (v: View) => void; token: string; onPreferencesSaved: () => void }) {
  const choices = ["Speak more clearly", "Organize my thoughts", "Find words faster", "Speak with more variety"]; const [selected, setSelected] = useState<string[]>([]); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  function toggle(choice: string) { setSelected(current => current.includes(choice) ? current.filter(item => item !== choice) : current.length < 2 ? [...current, choice] : current); }
  async function continueOnboarding() { setSaving(true); setError(null); try { await api.updatePreferences(token, { learningGoals: selected }); onPreferencesSaved(); go("baseline"); } catch (cause) { setError(cause instanceof ApiError ? cause.message : "We couldn't save your choices. Try again."); } finally { setSaving(false); } }
  return <div className="onboarding narrow"><Eyebrow>01 / 02</Eyebrow><h1>What would you like to improve?</h1><p>Select up to two areas. We’ll use this to tailor your first practice.</p><div className="choice-grid">{choices.map(choice => <button key={choice} type="button" className={`choice ${selected.includes(choice) ? "selected" : ""}`} aria-pressed={selected.includes(choice)} onClick={() => toggle(choice)}>{choice}<span>{selected.includes(choice) ? "✓" : "+"}</span></button>)}</div>{error && <p className="form-error" role="alert">{error}</p>}<Button onClick={continueOnboarding} disabled={saving}>{saving ? "Saving…" : "Continue"}</Button></div>;
}

export function Baseline({ go, token, onStarted }: { go: (v: View) => void; token: string; onStarted: () => Promise<void> }) {
  const [error, setError] = useState<string | null>(null); const [starting, setStarting] = useState(false);
  async function begin() { setStarting(true); setError(null); try { await api.startBaseline(token); await onStarted(); go("home"); } catch (cause) { setError(cause instanceof ApiError ? cause.message : "We couldn't start your baseline. Try again."); } finally { setStarting(false); } }
  return <div className="baseline narrow"><Eyebrow>Your starting point</Eyebrow><h1>Let’s find your<br /><i>baseline.</i></h1><p>You’ll complete three short speaking challenges. There are no right answers — this simply gives us a place to begin.</p><Card><span className="step-number">3</span><div><h3>Short challenges</h3><p>About 2 minutes each</p></div><span className="step-number">15</span><div><h3>Minutes total</h3><p>Take them when you’re ready</p></div></Card>{error && <p className="form-error" role="alert">{error}</p>}<Button onClick={begin} disabled={starting}>{starting ? "Starting…" : "Begin baseline"}</Button></div>;
}
