"use client";
import { useEffect, useState } from "react";
import { challenges, currentChallenge } from "../shared/mock-data";
import { Button, Card, Eyebrow } from "../ui/primitives";
import type { View } from "../ui/shell";
export function Practice({ go }: { go: (v: View) => void }) { return <div className="page"><Eyebrow>Practice library</Eyebrow><h1>Choose your next<br /><i>challenge.</i></h1><div className="challenge-list">{challenges.map(c => <Card key={c.id} className="challenge"><div><span className="pill">{c.difficulty}</span><h2>{c.title}</h2><p>{c.prompt}</p><span className="muted">{c.duration / 60} min · {c.targetSkills.join(" + ")}</span></div><Button variant="secondary" onClick={() => go("briefing")}>View challenge</Button></Card>)}</div></div>; }
export function Briefing({ go }: { go: (v: View) => void }) { return <div className="page briefing narrow"><button className="back" onClick={() => go("practice")}>← Practice</button><Eyebrow>Challenge 01 · Foundation</Eyebrow><h1>{currentChallenge.title}</h1><p className="prompt">{currentChallenge.prompt}</p><div className="meta-row"><div><span>Target duration</span><strong>2 minutes</strong></div><div><span>Skills</span><strong>Structure · Fluency</strong></div></div><Button onClick={() => go("prepare")}>Prepare to speak <span>→</span></Button></div>; }
export function Preparation({ go }: { go: (v: View) => void }) { const [notes, setNotes] = useState(""); return <div className="page preparation"><div className="narrow"><button className="back" onClick={() => go("briefing")}>← Challenge</button><Eyebrow>Take a moment</Eyebrow><h1>Prepare your<br /><i>thinking.</i></h1><p>Use this space to shape your response. These notes are private and won’t be evaluated.</p><ol>{currentChallenge.guidance.map(step => <li key={step}>{step}</li>)}</ol><label className="notes-label">Your notes <span>Optional</span><textarea value={notes} onChange={e => setNotes(e.target.value)} placeholder="A few prompts for yourself…" /></label><Button onClick={() => go("speak")}>I’m ready to speak</Button></div></div>; }
export function Speaking({ go }: { go: (v: View) => void }) { const [recording, setRecording] = useState(false); const [seconds, setSeconds] = useState(0); useEffect(() => { if (!recording) return; const id = window.setInterval(() => setSeconds(x => x + 1), 1000); return () => window.clearInterval(id); }, [recording]); const time = `${Math.floor(seconds / 60)}:${String(seconds % 60).padStart(2, "0")}`; return <div className="speaking"><button className="close" onClick={() => go("prepare")} aria-label="Exit recording">×</button><div className="speaking-prompt"><Eyebrow>Make the case</Eyebrow><p>{currentChallenge.prompt}</p></div><div className="recorder"><span className={recording ? "record-dot live" : "record-dot"} /><time>{time}</time><p>{recording ? "Speaking…" : "When you’re ready"}</p><button className={`record-button ${recording ? "stop" : ""}`} onClick={() => recording ? go("processing") : setRecording(true)} aria-label={recording ? "Stop and submit recording" : "Start recording"}><span /></button><small>{recording ? "Tap to finish" : "Tap to start"}</small></div></div>; }
export function Processing({ go }: { go: (v: View) => void }) { const [done, setDone] = useState(false); useEffect(() => { const id = window.setTimeout(() => setDone(true), 1800); return () => window.clearTimeout(id); }, []); return <div className="processing narrow"><div className="orb" /><Eyebrow>{done ? "Analysis complete" : "Analyzing your practice"}</Eyebrow><h1>{done ? "Your feedback is ready." : "Listening for what matters."}</h1><p>{done ? "We’ve separated the signals from the interpretation." : "We’re reviewing pacing, structure, and the moments that will help you improve."}</p>{done ? <Button onClick={() => go("results")}>View results</Button> : <div className="loading-line" />}</div>; }
